config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
resources :easy_custom_fields do
  collection do
    post :index
  end
  

end

resources :custom_fields do
  collection do
    post :rearrange_fields
  end
end

app/models/easy_custom_field.rb
class EasyCustomField < ActiveRecord::Base
  unloadable
end

app/controllers/easy_custom_fields_controller.rb
class EasyCustomFieldsController < ApplicationController
layout 'admin'

  before_filter :require_admin
  
  def index
  end
  
  def require_admin
    return unless require_login
    if !User.current.admin?
      render_403
      return false
    end
    true
  end
 
  
 helper :easy_custom_fields
 include EasyCustomFieldsHelper
  
end

app/helpers/easy_custom_fields_helper.rb
 module EasyCustomFieldsHelper
   include ApplicationHelper
end

app/views/custom_fields/_index.html.erb
<table class="list">
  <thead>
    <% if tab[:name] == 'IssueCustomField' %>
    <tr>
      <%= form_tag({}, :method => :get) do %>        
        <label for='custom_field_tracker'><%= l(:custom_field_tracker) %> :</label>
        <%= select_tag 'custom_field_tracker', tracker_options_for_select(@custom_field_tracker),
                                      :class => "small",:onchange => "this.form.submit(); return false;" %>
      <% end %>
    </tr>
    <% end %>
    
    <tr>
    <th><%=l(:field_name)%></th>
    <th><%=l(:field_field_format)%></th>
    <th><%=l(:field_is_required)%></th>
    <% if tab[:name] == 'IssueCustomField' %>
      <th><%=l(:field_is_for_all)%></th>
      <th><%=l(:label_used_by)%></th>
    <% end %>
    <th><%=l(:button_sort)%></th>
    <th></th>
  </tr></thead>
  <tbody id="sortable-custom-field">
  <% (@custom_fields_by_type[tab[:name]] || []).sort.each do |custom_field| -%>

    <tr class="<%= cycle("odd", "even")%>" id="<%= "#{custom_field.id}"%>" >
      <td class="name"><%= link_to h(custom_field.name), edit_custom_field_path(custom_field) %></td>
      <td><%= l(custom_field.format.label) %></td>
      <td><%= checked_image custom_field.is_required? %></td>
      <% if tab[:name] == 'IssueCustomField' %>
      <td><%= checked_image custom_field.is_for_all? %></td>
      <td><%= l(:label_x_projects, :count => custom_field.projects.count) if custom_field.is_a? IssueCustomField and !custom_field.is_for_all? %></td>
      <% end %>
      <td class="reorder"><%= reorder_links('custom_field', {:action => 'update', :id => custom_field}, :put) %></td>
      <td class="buttons">
        <%= delete_link custom_field_path(custom_field) %>
      </td>
    </tr>
  <% end; reset_cycle %>
  </tbody>
</table>


<script>
  
  
$( document ).ready(function() {
  
$( "#sortable-custom-field" ).sortable(
  { update: function(event, ui){
            
           //alert($( "#sortable" ).sortable('toArray'));
           var itm_arr = $("#sortable-custom-field").sortable('toArray');
           //var positions = {custom_fields: itm_arr};
           data: $(this).sortable("serialize"),
               $.ajax({
                   url: "/custom_fields/rearrange_fields",
                    data: {tab: 'IssueCustomField',custom_fields: itm_arr,
                   },
                   type: 'POST',         
                   failure: function (data) {
                       alert('Unable to Rearrange'+(data));
                   }

               });



               }

           });

    $( "#sortable-custom-field" ).disableSelection();
});
 

    </script>